prod/westeurope/siem/virtual_machine/terragrunt.hcl
Due to a replacement of the disk from a backup via azure portal.
=> [#172576720] Update reference disk name in vm siem

prod/westeurope/internal/api/functions_app/function_app/terragrunt.hcl
depends on https://github.com/pagopa/io-infrastructure-live-new/pull/161 (PR points there)
**Cannot be applied since it wants to reinstall the disabled sendgrid key** (cc @francescopersico)
I'm applying these settings manually, once merged we'll check again.
=> [#172989102] Add notification queue settings in io-functions-app

prod/westeurope/internal/appbackend/app_service/terragrunt.hcl, prod/westeurope/internal/appbackend/app_service_slot_staging/terragrunt.hcl
applied manually because it wants to change an extranoues setting:
`~ ftps_state                = "AllAllowed" -> "Disabled"`
PR targets #161 (not master)
=> [#172989315] Add notification queue settings to io-backend

prod/westeurope/external/apigateway/application_gateway/terragrunt.hcl, prod/westeurope/external/appgateway/application_gateway/terragrunt.hcl
Due to this issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/6188
You need to run terrafrom with a custom azure provider.
And this should be the change in the plan:
```
resource "azurerm_application_gateway" "application_gateway" {
enable_http2        = false
id                  = "/subscriptions/****************/resourceGroups/io-p-rg-external/providers/Microsoft.Network/applicationGateways/io-p-ag-apigateway"
location            = "westeurope"
name                = "io-p-ag-apigateway"
resource_group_name = "io-p-rg-external"
tags                = {}
zones               = []
+ autoscale_configuration {
+ max_capacity = 10
+ min_capacity = 2
}
```
=> [#172976853] Enable autoscaling in appgateway and apigateway

prod/westeurope/common/cdn/cdn_endpoint_assets/terragrunt.hcl, prod/westeurope/common/cdn/cdn_endpoint_assets_cdn_custom_domain/terragrunt.hcl, prod/westeurope/common/cdn/cdn_endpoint_assets_custom_domain/terragrunt.hcl
This PR contains the changes to configure the new CDN endpoint to serve static assets stored in a a $web container of a storage account.
In particular, the new CNAME `assets.cdn` in the DNS zone has been added to have the word "cdn" in the address and some delivery rules have beed defined to configure different caching expiration.   
The following URLs will need to be used to access the static resources when the whole solution is put in place: 
```
curl https://assets.cdn.io.italia.it/bonus/vacanze/bonuses_available.json -vvv
curl https://assets.cdn.io.italia.it/status/backend.json -vvv 
curl https://assets.cdn.io.italia.it/municipalities/A/0/A004.json -vvv 
curl https://assets.cdn.io.italia.it/services-data/visible-services.json -vvv  [TO DO]
...
...
```
all the files in the …
=> [#173352060] CDN endpoint for static assets

prod/westeurope/internal/api/apim/api_management/terragrunt.hcl, prod/westeurope/internal/api/apim/subnet/terragrunt.hcl
- update custom domain certificate from `io-italia-it` to `api-internal-io-italia-it `
- update to module source to version v2.0.36 to avoid subnet `address_prefixies` deprecation
```
terragrunt plan
~ hostname_configuration {
~ proxy {
~ default_ssl_binding          = false -> true
~ host_name                    = "io-p-apim-api.azure-api.net" -> "api-internal.io.italia.it"
+ key_vault_id                 = "XXXXX"
negotiate_client_certificate = false
}
- proxy {
- default_ssl_binding          = true -> null
- host_name                    = "api-internal.io.italia.it" -> null
- key_vault_id                 = "XXXXX" -> null
- negotiate_client_certificate = false -> null
}
}
~ resource "azurerm_api_management_property" "api_management_property" {
...
+ value               = …
```
=> [#174649420] Update apim custom domain certificate

prod/westeurope/internal/api/apim/api_management/terragrunt.hcl
Version of the module 2.0.40 includes this fix:
https://github.com/pagopa/io-infrastructure-modules-new/pull/147
I've already changed the state file running manually terraform import and terraform state rm.
```
No changes. Infrastructure is up-to-date.
This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```
=> [#173830662] Fix arning azurerm_api_management_property deprecated

prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
Allow `io-functions-admin` to write on Subscriptions Feed by introducing the following environment variables:
| Variable name                    | Description                                                                                      | type   |
|----------------------------------|--------------------------------------------------------------------------------------------------|--------|
| SubscriptionFeedStorageConnection| Storage connection string for subscription feed                                                  | string |
| SUBSCRIPTIONS_FEED_TABLE         | Table name for the Subscriptions Feed in the storage                                             | string |  
This PR blocks https://github.com/pagopa/io-functions-admin/pull/81
=> [#174824788 ] Add connection to subscriptions feed to fns-admin

prod/westeurope/external/firewall_custom_rules/terragrunt.hcl
This has been already applied, but not associated to the application gateway.
=> [#175183727] Custom WAF rules to apply to appgateway

prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
As we are unifying utilities to send emails from our functions apps, we need to rename `MAIL_FROM_DEFAULT` app setting into `MAIL_FROM`. 
We keep them both as we didn't deploy the code yet, we then need to remove `MAIL_FROM_DEFAULT` once the related changes on `io-functions-services` land to production.
=> [#175225851] Add MAIL_FROM application settings on io-functions-services

prod/westeurope/internal/api/apim/api_management_api_services/swagger.json.tmpl
This PR contains an update of io-functions-services exposed API `uploadOrganizationLogo`
=> [#175395536] Allow uploadOrganizationLogo API on io-fn-services

prod/westeurope/internal/api/functions_app_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_assets_r3/function_app_slot_staging/terragrunt.hcl
Due to changes that will be introduced in [this PR](https://github.com/pagopa/io-functions-assets/pull/13), the swap is going to be executed by the deploy pipeline.
=> [#175126219] Disable autoswap on io-function-assets

prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
Due to changes that will be introduced in [this PR](https://github.com/pagopa/io-functions-services/pull/90), the swap is going to be executed by the deploy pipeline.
=> [#175126219] Disable autoswap on io-function-services

prod/westeurope/internal/api/functions_public_r3/function_app_slot_staging/terragrunt.hcl
Due to changes that will be introduced in [this PR](https://github.com/pagopa/io-functions-public/pull/21), the swap is going to be executed by the deploy pipeline.
=> [#175126219] Disable autoswap on io-function-public

prod/westeurope/internal/api/functions_app_r3/function_app_slot_staging/terragrunt.hcl
Due to changes that will be introduced in [this PR](https://github.com/pagopa/io-functions-app/pull/117), the swap is going to be executed by the deploy pipeline.
=> [#175126219] Disable autoswap on io-function-app

prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
```
sku_size = P2v2
FETCH_KEEPALIVE_MAX_SOCKETS = 80
```
only on appbackendl1 and appbackendl2
appbackendli is in production and change this settings will restart the vm machines
=> Tuning appbackends linux FETCH_KEEPALIVE_MAX_SOCKETS and sku_size

prod/westeurope/common/cdn/cdn_endpoint_resources/terragrunt.hcl, prod/westeurope/common/cdn/storage_account_resources/terragrunt.hcl
**Description**
This PR proposes to add a new endpoint to the cdn to serve static assets/resources. The endpoint is linked to the storage account `storage_account_resources` configured to serve static web files. Despite being deprecated, an endpoint `assets` is already in place in the infrastructure, so for the sake of simplicity in naming patterns, I chose the totally different name `resources`.
**Proposed changes**
- New cdn endpoint `resources`
- New storage account `storage_account_resources` to serve static web files
**How to test**
This PR is just a proposal. I haven't actually tested it
=> [#176008623] Added new cdn endpoint "resources" and related storage account

prod/westeurope/internal/api/apim/api_management_api_io_payportal/policy.xml
The purpose of this PR is to fix the content type name allow set into apim of `io-pay-portal`
Switch from `contentType` to `Content-Type` see also [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)
=> [#176140405] fix content type name `io-pay-portal`

prod/westeurope/internal/api/apim/api_management_api_backoffice/policy.xml
limits:
- 20 requests from same ip address in 30 seconds
- 8 requests search using fiscal code in 60 seconds per user (one search on backoffice UI needs 4 api requests, so 8 requests equals 2 searches by fiscal code)
sample response:
```
{
"statusCode": 429,
"message": "Rate limit is exceeded. Try again in 19 seconds."
}
```
=> [#176208498] Fiscal code rate limit policy

prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
These changes are needed in order to allow the deploy pipeline to reach the `/info` endpoint for each of the three app services.
=> [#176738538] Allow Azure DevOps subnet for appbackend instances, remove BONUS_REQUEST_LIMIT_DATE, setted valid API_URL

prod/westeurope/cgn/function_cgn/function_app_slot_staging/terragrunt.hcl
Enable Azure DevOps vnet for the staging slot of CGN function app. This needed by https://github.com/pagopa/io-functions-cgn/pull/15 to perform healthcheck on the staging slot before swapping.
=> [#175897066] Allow azure devops vnet for CGN

prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl, prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl, prod/westeurope/cgn/storage_cgn/table_eycacardexpiration/terragrunt.hcl
This PR adds:
- A new env variable `EYCA_EXPIRATION_TABLE_NAME` that defines the new table name, both in `prod` and `staging` environment.
- A new table `eycacardexpiration` into the storage
=> [#176924877] Add Expiration Date Table for Eyca Card

prod/westeurope/support/functions_backoffice/function_app/terragrunt.hcl
this pr add CSTAR configuration to call api exposed from CSTAR APIM
Related PR:
https://github.com/pagopa/io-functions-backoffice/pull/56
Status: not applied
=> [#BOP-10] Add CSTAR APIM configuration to fn-backoffice

prod/westeurope/internal/api/apim/api_management_api_io_payportal/policy.xml, prod/westeurope/internal/api/apim/api_management_api_io_payportal/swagger.json.tmpl
The goal of this PR is to configure a new endpoint exposed through apim to support the new api of [io-pay-portal](https://github.com/pagopa/io-pay-portal/pull/22).
1. Updated apim spec for _io-pay-portal_.
2. Updated apim policy to accept requests from _io.italia.it_.
=> [#VF-10] Added new apim endpoint to support newsletters API

prod/westeurope/internal/api/apim/api_management_api_backoffice/policy.xml
this pr update rate limit to call api with fiscal code.
We add a new api call so we need to increase rate-limit from 6 to 8 per minute
Also it is fixed `Content-Type` header
Status: not applied
=> [#BOP-13] Update rate limit api backoffice

prod/westeurope/internal/api/apim/api_management_api_io_payportal/policy.xml, prod/westeurope/internal/api/apim/api_management_api_io_payportal/swagger.json.tmpl, prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
This PR introduces some updates related to the [io-pay-portal](https://github.com/pagopa/io-pay-portal) configuration.
1.  Updated apim spec for _io-pay-portal_ according to [this](https://github.com/pagopa/io-pay-portal/pull/27) refactoring;
2. Updated apim policy to accept requests from _https://www.pagopa.gov.it/_;
3. Added `MAILUP_ALLOWED_GROUPS` and `MAILUP_ALLOWED_LISTS` envs variables;
4. Rename secret `newsletter-GOOGLE-RECAPTCHA-SECRET` in `newsletter-GOOGLE-RECAPTCHA-SECRET-IO`
5. Added new secret `newsletter-GOOGLE-RECAPTCHA-SECRET-PAGOPA`
=> [Vf-10] Updated configuration for newsletters api - io-pay-portal

prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
This PR add new env variable `IO_PAY_ORIGIN` used by `io-pay-portal` function in `api/v1/transactions/{id}/method`
=> [IOPAY-86] add `IO_PAY_ORIGIN ` var env

prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
This PR disable `ContinueEycaActivation` Queue triggered functions in order to avoid wrong staging execution due to access to a single queue.
=> [#177494601] Disable CGN Queue triggered functions on staging slot

prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl, prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
Configure `io-p-fn3-pushnotif` to use production queue and notification hub. 
These changes are in preparation of the traffic switch from `io-p-fn3-appasync` to `io-p-fn3-pushnotif`. At the moment the latter has the handler disabled, so that it won't consume events from notification queue. 
Sandbox resources are kept for further development-time tests.
---
=> [#IP-49] Use production resources for fn-pushnotif

prod/westeurope/internal/api/apim/api_management_api_io_payportal/policy.xml
This PR adds a new origin for _io-pay-portal apim_, which is the endpoint of an issuer in the _3ds2 payment flow._ 
- added  endpoint of an issuer  configured with _localhost_ to perform a first test with the production _frontend/function io-pay_ and the Payment Manager API locally (awaiting deployment in the _uat_ environment)
=> [IOPAY-85] Add test issuer endpoint for io-pay-portal

prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl, prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl, prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
This PR is draft as it needs #486 before applying.
* Disable `HandleNHNotificationCall` on `io-p-fn3-appasync`
* Enable `HandleNHNotificationCall` on `io-p-fn3-appasync`
To move traffic from `io-p-fn3-appasync` to `io-p-fn3-pushnotif`, with the plan to dismantle the first. 
Changes must be applied in the following order:
* first disable
* the enable
This is to avoid both functions to consume the same messages con currentlty.
unwanted changes on `io-p-fn3-appasync`:
- version = "3.0.13353.0" -> "~3"
- add "azurerm_template_deployment" "versioning"
they are safe to apply, we can consider an update to terraform configuration (no breaking changes)
---
=> [#IP-49]  Switch notification traffic from fn3-appasync to fn3-pushnotif

prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl, prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
* add `RETRY_ATTEMPT_NUMBER` to `io-p-fn3-pushnotif`
* add `APPINSIGHTS_SAMPLING_PERCENTAGE` to `io-p-fn3-pushnotif`
It's introduced by https://github.com/pagopa/io-functions-pushnotifications/pull/4
---
=> [#IP-44] add RETRY_ATTEMPT_NUMBER, APPINSIGHTS_SAMPLING_PERCENTAGE variables

prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/swagger.json.tmpl, prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_policy/policy.xml, prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_policy/terragrunt.hcl, prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_verification_policy/policy.xml, prod/westeurope/internal/api/apim/api_management_api_io_payportal/get_transactions_xpay_verification_policy/terragrunt.hcl
- add new api `/transactions/xpay/{id}` and `/transactions/xpay/verification/{id}` in `api_management_api_io_payportal/api/swagger.json.tmpl`;
- add new policy for `/transactions/xpay/{id}`;
- add new policy for `/transactions/xpay/verification/{id}`;
The purpose of this PR is to configure two new API to support payments in [io-pay](https://github.com/pagopa/io-pay) with Xpay cards ([io-pay xpay flow](https://pagopa.atlassian.net/wiki/spaces/I/pages/84934691/Analisi+tecnica+IO-Pay#4.-IO-PAY---focus-flusso-3ds2-(nexi))). 
---
=> [IOPAY-111] Add apim config to support xpay flow

prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
-  Add new env variable `PAY_PORTAL_RECAPTCHA_SECRET` from secrets;
This new variable is necessary to differentiate the Recaptcha Google secret  for newsletters (_io.italia.it_ and _www.pagopa.gov.it_) and the one used by the payment portal (_paga.io.italia.it_).
- [n] No
---
=> [IOPAY-97] Add new env for recaptcha secret - pay portal

prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
- New env variable `IO_PAY_XPAY_REDIRECT` to support _xpay_ redirect to _io-pay_.
The new variable `IO_PAY_XPAY_REDIRECT` is used by `io-pay-portal` to construct the return url to _io-pay_ from  _xpay_ .
---
=> [IOPAY-111] New env to support xpay redirect to io-pay

prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/policy.xml, prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
- Updated origins of _apim_io_pay_portal_ with:
- https://paga.io.italia.it
- https://checkout.pagopa.gov.it
- Update app setting of io-functions_pay_portal:
- `IO_PAY_CHALLENGE_RESUME_URL`
- `IO_PAY_ORIGIN`
- `IO_PAY_XPAY_REDIRECT`
The goal of this PR is to align allowed origin and url for _3ds2 payment flow_ to production values.
---
=> [IOPAY-173] Update checkout.pagopa.gov.it origin

prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl, prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
Addend new NH env variables both to staging and prod _io-functions-pushnotification_
In order to switch to new NH management, we need to add new env variables related to the new Notification Hubs
---
=> [IP-146] Add env variable to prod and staging

prod/westeurope/notifications/sandbox/notification_hub-partition-1/terragrunt.hcl, prod/westeurope/notifications/sandbox/notification_hub/terragrunt.hcl
- Switch to Sandbox APNS server 
In order to successfully test push notifications in iOS development mode, we need to switch to Sandbox APNS server
---
=> switch to APNS sandbox in test Notification Hubs

prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/policy.xml
- Delete _cdn_ origin in apim _io-pay-portal_ config;
The goal of this PR is to delete unnecessary _cdn_ origin in apim _io-pay-portal_ config.
---
=> [IOPAY-221] Delete cdn origin in apim config

prod/westeurope/internal/api/apim/api_management_api_services/swagger.json.tmpl
Update APIM OpenAPI spec for `SERVICE API` to latest development:
* align with previous model refactoring in https://github.com/pagopa/io-infrastructure-live-new/commit/5ae7f2118e2bcbf7a128e4baf12fc5cca1038703
* introduce 403 for APIs that need it
We introduced 403 in https://github.com/pagopa/io-functions-services/pull/125 and we needed to apply same changes to APIM. While doing so, we realized we haven't updated spec for long, so we brought those changes in as well
---
=> Ip 210  add 403 to openapi spec

prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl, prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl, prod/westeurope/eucovidcert/storage_eucovidcert/account/terragrunt.hcl, prod/westeurope/eucovidcert/storage_eucovidcert/queue_notify-new-profile-poison/terragrunt.hcl, prod/westeurope/eucovidcert/storage_eucovidcert/queue_notify-new-profile/terragrunt.hcl, prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl, prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/storage_apievents/account/terragrunt.hcl, prod/westeurope/internal/api/storage_apievents/queue_eucovidcert-profile-created/terragrunt.hcl
1. add storage_apievents and queue_eucovidcert-profile-created
2. add config to fn-app
3. add config to fn-eucovidcert
Resources for eucovidcert notify flow
---
=> Add configs eucovidcert notify new users

prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
Fix eucovidcert backend base path to     `/api/v1/eucovidcert`
Bugfixing
---
=> Fix eucovidcert backend base path

prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl, prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl, prod/westeurope/notifications/sandbox/storage_notifications/queue_push-notifications/terragrunt.hcl
* add `TEST_LOGIN_FISCAL_CODES` env var to `fn3-pushnotif`
We want to blacklist load test user to not overuse public notification services
---
=> add load test users in notifications blacklist

prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
* disabled `OnProfileCreatedEvent` and `NotifyNewProfileToDGC` on `fn3-eucovidcert` staging slot
So that staging slot does not consume messages from production queue
---
=> [#IPV-64] Disable queue listeners on `fn3-eucovidcert` staging slot

prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/services/functions_services01_r3/function_app/terragrunt.hcl, prod/westeurope/services/functions_services01_r3/function_app_slot_staging/terragrunt.hcl
- add `FF_DISABLE_WEBHOOK_MESSAGE_CONTENT = "true"`
https://github.com/pagopa/io-functions-services/pull/131
---
=> [#IP-234] Disable message content for WEBHOOK channel

prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl, prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl, prod/westeurope/eucovidcert/storage_eucovidcert/table-trace-notify-new-profile/terragrunt.hcl
* create table `trace-notify-new-profile` into `iopsteucovidcert`
* reference the table in app using env var
For easy support and throubleshooting, we will need to trace all events occurred in the process of notify a new profile to DGC
---
=> [#IPV-97] Add table storage to trace EU Covid Cert events

prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl, prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl
- `FF_NEW_USERS_EUCOVIDCERT_ENABLED = true`
Enable Notify new users to DGC service
---
Wait to apply this PR
=> Enable fnapp FF_NEW_USERS_EUCOVIDCERT_ENABLED

prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
Need some env variables for JWT API for MIT Voucher (called often "Sicilia Vola") to integrate remote SOGEI API by federation pattern.
You can read confluece pages: https://pagopa.atlassian.net/l/c/ovpwSi28
- IO BackEnd https://github.com/pagopa/io-backend/pull/807
Due a contract with MIT we need to implement a national service on IO App about flight vouchers for sicilian citizens. Origin backend was implemented by SOGEI and we need integrate a secure connection using a JWT.
no
no
=> [#ISV-29] Enable Mit Voucher Jwt Token

prod/westeurope/internal/api/cosmosdb/container_notification-status/terragrunt.hcl
Set max_throughput to previous value: 10000
No apply needed
Apply fail with this error:
The offer should have valid throughput values between 12000 and 1000000 inclusive in increments of 1000.
Notification status is now 97GB so probably we can't scale down to 7000 RU/s
https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#limits-for-autoscale-provisioned-throughput
---
=> fix notification-status

prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl, prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_assets_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_assets_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_public_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_public_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/internal/api/functions_servicescache_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_servicescache_r3/function_app_slot_staging/terragrunt.hcl, prod/westeurope/services/functions_services01_r3/function_app/terragrunt.hcl, prod/westeurope/services/functions_services01_r3/function_app_slot_staging/terragrunt.hcl
add azure functions app settings to route all traffic in private VNET using private dns zones
```
WEBSITE_DNS_SERVER     = "168.63.129.16"
WEBSITE_VNET_ROUTE_ALL = 1
```
limits comosapi network access
---
=> [#IOINFRA-173] Configure functions's routing and DNS to access cosmos-api

prod/westeurope/common/private_dns_zones/privatelink-blob-core-windows-net/virtual_network_link_vnet-vpnp2s/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-documents-azure-com/virtual_network_link_vnet-common/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-documents-azure-com/virtual_network_link_vnet-vpnp2s/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-file-core-windows-net/virtual_network_link_vnet-common/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-file-core-windows-net/virtual_network_link_vnet-vpnp2s/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-queue-core-windows-net/virtual_network_link_vnet-common/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-queue-core-windows-net/virtual_network_link_vnet-vpnp2s/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-table-core-windows-net/virtual_network_link_vnet-common/terragrunt.hcl, prod/westeurope/common/private_dns_zones/privatelink-table-core-windows-net/virtual_network_link_vnet-vpnp2s/terragrunt.hcl, prod/westeurope/vpnp2s/dns_forwarder/server/terragrunt.hcl, prod/westeurope/vpnp2s/dns_forwarder/subnet/terragrunt.hcl, prod/westeurope/vpnp2s/resource_group/terragrunt.hcl, prod/westeurope/vpnp2s/virtual_network/terragrunt.hcl
- add resource group vpnp2s (imported)
- add vnet vpnp2s (imported)
- add dns forwarder vpnp2s
- add vpnp2s private links to private dns zones
now dns forwarder works even if vnet-common is in maintenance mode
---
=> Add dns forwarder in vpnp2s vnet

prod/westeurope/functions_app1/functions_app1_r3/subnet/terragrunt.hcl, prod/westeurope/internal/api/functions_admin_r3/subnet/terragrunt.hcl, prod/westeurope/internal/api/functions_app2_r3/subnet/terragrunt.hcl, prod/westeurope/internal/api/functions_app_async/subnet/terragrunt.hcl, prod/westeurope/internal/api/functions_assets_r3/subnet/terragrunt.hcl, prod/westeurope/internal/api/functions_public_r3/subnet/terragrunt.hcl, prod/westeurope/internal/api/functions_services_r3/subnet/terragrunt.hcl, prod/westeurope/internal/api/functions_servicescache_r3/subnet/terragrunt.hcl, prod/westeurope/internal/api/storage/account/terragrunt.hcl, prod/westeurope/services/functions_services01_r3/subnet/terragrunt.hcl
add firewall rules with whitelist resources
1. io-p-fn3-admin
2. io-p-fn3-app1
3. io-p-fn3-app2
4. io-p-fn3-appasync
5. io-p-fn3-assets
6. io-p-fn3-public
7. io-p-fn3-services
8. io-p-fn3-services01
9. io-p-fn3-servicescache
close iopstapi public access
---
=> [#IOINFRA-184] Add whitelist resources to access iopstapi

prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
* update `linux_fx_version` to `14-lts`
* remove useless `WEBSITE_NODE_DEFAULT_VERSION` app setting
We needed to upgrade Node runtime to the latest available version. Unfortunately, we found out **we cannot pin to a specific version**, but we must use what the app service is bound to (`14.15.1` at the time of writing).
Also, we removed `WEBSITE_NODE_DEFAULT_VERSION` as we understood it does not affect the runtime version.
---
=> [#IP-346] Update Node version for `appbackend`

prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
- add UAT _Payment Manager_ host in io-pay _Content Security Policy_, in particulat in `connect-src`
The goal of this PR is to add the Payment Manager host into the Content Secury Policy of io-pay cdn, for testing purposes.
---
=> [IOPAY] update csp to allow connection from uat PM env

prod/westeurope/internal/api/storage_user-data-download/account/terragrunt.hcl, prod/westeurope/internal/api/storage_user-data-download/management_policy/terragrunt.hcl
* add a retention policy of 14 days 
* remove previous configuration (not working)
Although we have a business rule for data portability bundle to be available for no longer that 14 days, we have evidence they are still reachable after such period.
The main cause seems to be the `blob_properties_delete_retention_policy_days` attribute not to work as intended (it should set a soft-delete retention policy).
As we have no actual need to recover such blobs after they're deleted, we can use a hard-delete policy, which is proven to work in many other scenarios we have.
---
=> [#IP-429] Add policy for hard delete user data blobs

prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
Add a new FF to enable login age limit in `io-backend`
We need a progressive rollout in production for the new feature. Maybe we will set to enabled this FF manually and apply this PR when all the tests will be completed.
---
=> [#IC-109] Add Feature flag for login age limit

prod/westeurope/common/nat_gateway/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl, prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
- add appbackend's subnets to nat gateway
- add `WEBSITE_VNET_ROUTE_ALL` and `WEBSITE_DNS_SERVER` to appbackends
use fixed outgoing ip for appbackends
---
=> [INFRA-372] Add nat gateway for app backend

prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
- add MIN_APP_VERSION_WITH_READ_AUTH variable
Allow fn-services to check user's app version with the minimum version that introduced the read status opt-out feature  
---
=> [#ICC-101] add MIN_APP_VERSION_WITH_READ_AUTH to fn-services

prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl, prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
- set MIN_APP_VERSION_WITH_READ_AUTH to 2.13.0
Set pivot version for enabling getMessage to return read status in case of advanced messages, if applicable
---
=> [#ICC-147] set MIN_APP_VERSION_WITH_READ_AUTH to 2.13.0

prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl, prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
Re-implement the NotifyMessage orchestrator/activity (io-functions-pushnotif) without the Durable Function.
The NotifyMessage operation will be implemented used a storage queue: the retry mechanism will be provided by the azure function trigger.
Add new notify-message queue to inner storage
Add Feature Flag for notify via queue to app settings
The DF-based notify message performance are not enough reliable.
---
=> [#ICC-159] Add notify-message queue and poison to notify message without DF
