pagopa/io-infrastructure-live-new

- prod/westeurope/internal/api/functions_app/function_app/terragrunt.hcl
- prod/westeurope/internal/appbackend/app_service/terragrunt.hcl
- prod/westeurope/operations/storage_queue_spid_logs/terragrunt.hcl
Already applied, ready to be merged.
> [#171966534] Add variables to setup SPID logs

- prod/westeurope/internal/api/functions_services/function_app/terragrunt.hcl
- prod/westeurope/internal/appbackend/app_service/terragrunt.hcl
> [#172041729] set ALLOW_NOTIFY_IP_SOURCE_RANGE to io-function-services source addresses

- prod/westeurope/internal/api/functions_app/function_app/terragrunt.hcl
added DPOMailAddress to io-functions-app variables configuration
> [#172161469] Add DPO email address to io-functions-app settings

- prod/westeurope/internal/api/functions_app/function_app/terragrunt.hcl
> [#172403489] add SPID logs public key in io-functions-app

- prod/westeurope/internal/api/functions_app/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services/function_app/terragrunt.hcl
not applied yet, must be applied before or after merging
> [#172227332],[#172454561] Add keepalive configuration to functions

- prod/westeurope/internal/api/storage_notifications/account/terragrunt.hcl
- prod/westeurope/internal/api/storage_notifications/queue_push-notifications/terragrunt.hcl
> [#172989035] Add storage account and queue for push notifications

- prod/westeurope/internal/api/cosmosdb_bonus/account/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app_slot_staging/terragrunt.hcl
> [#173279617] add cosmosdb conn string to io-function-bonus settings

- prod/westeurope/internal/api/functions_bonus/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/storage_bonus/queue_bonusactivations/terragrunt.hcl
- prod/westeurope/internal/api/storage_bonus/table_adelogs/terragrunt.hcl
- prod/westeurope/internal/api/storage_bonus/table_bonusactivations/terragrunt.hcl
- prod/westeurope/internal/api/storage_bonus/table_bonusleasebindings/terragrunt.hcl
- prod/westeurope/internal/api/storage_bonus/table_eligibilitychecks/terragrunt.hcl
- prod/westeurope/internal/api/storage_bonus/table_inpslogs/terragrunt.hcl
> [#173471504] Add tables and queue for io-functions-bonus

- prod/westeurope/common/dns_caa_record/terragrunt.hcl
> [#173749503] Fix Name in the dns caa record

- prod/westeurope/internal/api/functions_admin/function_app/terragrunt.hcl
> Fix: user data download URL path

- prod/westeurope/internal/appbackend/app_service/terragrunt.hcl
- prod/westeurope/internal/appbackend/app_service_slot_staging/terragrunt.hcl
> Add backend session endpoint allowed CIDR

- prod/westeurope/internal/api/functions_admin/function_app/terragrunt.hcl
> [#172884867] Env vars for automatic user data delete

- prod/westeurope/internal/api/functions_admin/function_app/terragrunt.hcl
@gunzip I see that in production is set **FF_ENABLE_USER_DATA_DELETE = 1**, do you need it?
> [#174275746] Set USER_DATA_DELETE_DELAY_DAYS to 6 days

- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonusapi_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
> [#174337332] Fix module-azurerm_function_app_slot error ref Id

- prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl
On production slot functions must be enabled.
> Fix disabled functions on fn3-admin

- prod/westeurope/internal/api/functions_app_r3/function_app_slot_staging/terragrunt.hcl
We split this PR https://github.com/pagopa/io-infrastructure-live-new/pull/228 in subtask.
> [#174693987] Add functions_app_r3 staging slot

- prod/westeurope/internal/api/functions_assets_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_assets_r3/function_app_slot_staging/terragrunt.hcl
Adding SERVICES_BY_SCOPE_BLOB_ID
> Add env variable to io-functions-assets

- prod/westeurope/internal/api/apim/api_management_api_admin/swagger.json.tmpl
This PR contains a brand new endpoint for io-functions-admin API
> [#175395536] Add upload organization logo endpoint

- prod/westeurope/common/subnet_azure_devops/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
steps to apply:
1. create azure devops subnet
2. allow azure devops subnet on fn-admin staging slot
> [#175495707] Add azure devops subnet and allow it in fn-admin staging slot

- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
Apply only after this PR review is completed https://github.com/pagopa/io-functions-admin/pull/104
> [#175495717] Disable autoswap on fn-admin

- prod/westeurope/internal/appbackend/app_service/terragrunt.hcl
- prod/westeurope/internal/appbackend/app_service_slot_staging/terragrunt.hcl
This PR contains 3 new variables to be added on io-backend, in order to allow Support Token generation
> [#175679733] Add variables to io-backend for BPD

- prod/westeurope/internal/developerportalbackend/app_service/terragrunt.hcl
This PR add a new env variable for Dev Portal:
- LOGO_URL
> [#175892280] Add env LOGO_URL for Dev Portal

- prod/westeurope/internal/api/functions_assets_r3/function_app_slot_staging/terragrunt.hcl
> [#175905841] Devops subnet allowed access in assets function app slot

- prod/westeurope/internal/api/functions_bonus/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonusapi_r3/function_app_slot_staging/terragrunt.hcl
> [#175988021] Remove APPINSIGHTS_SAMPLING_PERCENTAGE in slot function

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendlinux/app_service/terragrunt.hcl
> Appbackend L1 and L2  split fn3app

- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/subnet/terragrunt.hcl
- subnet applied
- fn3appasync not applied
- fn3appasync slot staging not applied
> Add fn3appasync

- prod/westeurope/common/cdn/cdn_endpoint_backoffice/terragrunt.hcl
Add first version of CSP to backoffice portal.
Subject to further refinements once we understand more the context of:
https://github.com/ljharb/get-intrinsic/issues/3
> Add content-security-policy to backoffice portal

- prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
> [#176165582] Fix SESSION_API_URL

- prod/westeurope/common/redis/redis_cache/terragrunt.hcl
Not applied yet. 
So far I'm thinking to plan Sunday at 23.00 (00:00 CET)
> [#176167652] Set redis patch window

- terragrunt.hcl
Update terraform provider azurerm to version v2.41.0
> [#176243325] update terraform provider

- prod/westeurope/common/cdn/storage_account_assets/terragrunt.hcl
- prod/westeurope/common/redis/redis_cache/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/account/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/account/terragrunt.hcl
- prod/westeurope/operations/storage_account_logs/account/terragrunt.hcl
> [#176268678] Lock main data resources

- prod/westeurope/internal/api/apim/api_management_api_backoffice/swagger.json.tmpl
From
https://github.com/pagopa/io-functions-backoffice/blob/master/openapi/index.yaml
> [#176280091] Update swagger backoffice api

- prod/westeurope/internal/inpsproxy/app_service/terragrunt.hcl
- prod/westeurope/internal/inpsproxy/app_service_plan/terragrunt.hcl
This resource was created manually from the portal.
Now it has been imported in terraform
> [#176393885] App service inpsproxy

- prod/westeurope/cgn/resource_group/terragrunt.hcl
> [#176456197] New resource group for CGN project

- prod/westeurope/cgn/storage_cgn/account/terragrunt.hcl
- prod/westeurope/cgn/storage_cgn/table_cardexpiration/terragrunt.hcl
@AleDore  do we need to create here a table or a container within the account?
Any recommendation for the name?
> [#176456197] New storage account for cgn

- prod/westeurope/cgn/cosmosdb/account/terragrunt.hcl
- prod/westeurope/cgn/cosmosdb/database/terragrunt.hcl
- prod/westeurope/cgn/cosmosdb/private_dns_a_record/terragrunt.hcl
- prod/westeurope/cgn/cosmosdb/private_endpoint/terragrunt.hcl
> [#176456229] CosmosDB for cgn

- prod/westeurope/internal/api/functions_bonus/function_app/terragrunt.hcl
> [#176496461] Func bonus change plan 2 EP1

- prod/westeurope/cgn/cosmosdb/container_cgn/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_message-status/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_messages/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_notification-status/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_notifications/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_profiles/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_sender-services/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_services/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_user-data-processing/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/container_bonus_activations/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/container_bonus_leases/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/container_bonus_processing/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/container_eligibility_checks/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/container_user_bonuses/terragrunt.hcl
The autosceling was enabled manually since was not supported by the provider.
It's supported now.
> [#176500067] Comsmosdb colloections autoscaling

- prod/westeurope/operations/storage_account_exportdata/account/terragrunt.hcl
- prod/westeurope/operations/storage_account_exportdata/container_dfout/terragrunt.hcl
this pr add a storage account and container to save exported data from azure data factory
> [#176514097] Add exportdata storage account

- prod/westeurope/common/adgroups/security/terragrunt.hcl
> [#176536586] New AD group security

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
This PR adds and re-align some specific env variable, in order to start functions correctly.
> [#175897066] Func CGN update env variables

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
This PR adds 3 brand new env variables used to call EYCA CCDB API.
> [#176924278] Add EYCA CCDB API env variables

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/cgn/redis/redis_cache/terragrunt.hcl
This PR adds a Standard Redis configuration to io-functions-cgn
> [#177116784] Add Redis config to io-fn-cgn

- prod/westeurope/support/private_dns_zone_cstar_pagopa/virtual_network_link_vnet/terragrunt.hcl
- prod/westeurope/support/private_dns_zone_cstar_pagopa/zone/terragrunt.hcl
- prod/westeurope/support/route_table/terragrunt.hcl
Network configurations to reach cstar apim
Status: not applied
> [#BOP-12] Add DNS and routing for fn-backoffice to reach cstar apim

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
This PR adds an ENV var used to define OTP TTL for CGN online's discount
> [#177167655] Add CGN OTP TTL

- prod/westeurope/cgn/functions_cgn_merchant/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/subnet/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/web_test/terragrunt.hcl
This PR adds a new Function, used to expose API through external merchant systems.
> [#177224189] Add Function for exposing CGN API to merchants

- prod/westeurope/support/functions_backoffice/function_app/terragrunt.hcl
This PR adds inbound VNET restrictions. I'm going to apply this pr in not working hours
Status: not applied
> [BOP-19] Add vnet restrictions to fn-backoffice

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
This PR enables CGN Beta test for a provided set of Fiscal Codes.
> [#177137914] Add CGN Beta Test Fiscal Codes

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
This PR enables CGN API endpoint to be mounted on IO Backend.
> [#177454556] Enable CGN Feature Flag

- prod/westeurope/cgn/storage_cgn/queue_eycaactivations/terragrunt.hcl
- Add terra grunt script file for EYCA activation queue
Adding queue definition for EYCA activation
---
> [#177454556] Add EYCA activation queue

- prod/westeurope/internal/api/functions_assets_r3/function_app/terragrunt.hcl
Change app service plan from EP2 to EP1
cost saving
---
> [#IOINFRA-49] Scale down fn-assets

- prod/westeurope/external/apigad/app_service/terragrunt.hcl
Change app service plan from P3v2 to P2v2
Cost saving
Check plan, maybe there are unwanted changes
---
> [#IOINFRA-50] Scale down api-gad

- prod/westeurope/linux/appbackendli/autoscaling/terragrunt.hcl
- update minimum appbackendli instances from 5 to 3 
cost saving
---
> [#IOINFRA-52] Scale in appbackendli

- prod/westeurope/common/key_vault/terragrunt.hcl
- prod/westeurope/operations/key_vault_azuredevops/key_vault/terragrunt.hcl
- prod/westeurope/operations/key_vault_azuredevops/monitor/terragrunt.hcl
1. send `AuditEvent` logs to log analytics
2. upgrade keyvaults to module v3.0.4 that removes soft_delete_enabled variable (enabled by default in azure) https://github.com/pagopa/io-infrastructure-modules-new/blob/v3.0.4/CHANGELOG.md#v304
Apply azure security recommendations
`soft_delete_enabled = true` will be enabled by default on azure key-vault and will be deprecated in terraform provider 3.0.
---
> [#IOINFRA-54] Update azure devops keyvault configuration

- prod/westeurope/support/functions_backoffice/function_app/terragrunt.hcl
- prod/westeurope/support/private_dns_zone/zone/terragrunt.hcl
add new private dns record u87psqlp01-rep2
Switch to new replica2 postgresql
---
> [#IOINFRA-65] Dns record 2dn read replica db support

- prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
- Rewrite rule _http_ to _https_ for _io-pay_ endpoint;
The goal of this PR is to force the redirect http to https for _io-pay_ endpoint;
---
> [IOPAY-151] Rewrite http to https for io-pay

- prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
- enabled HTTP Strict Transport Security (HSTS) Policy for _io-pay_ cdn-endpoint;
---
> [IOPAY-151] Enable HTTP Strict Transport Security (HSTS) Policy for io-pay

- prod/westeurope/internal/api/functions_servicescache_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_servicescache_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_servicescache_r3/subnet/terragrunt.hcl
- prod/westeurope/internal/api/functions_servicescache_r3/web_test/terragrunt.hcl
Add new function app io-functions-services-cache https://github.com/pagopa/io-functions-services-cache
We disabled UpdateVisibleServicesCache for performance impacts on fn3-admin https://github.com/pagopa/io-infrastructure-live-new/pull/496
This function will contains all async jobs to update services
---
> [#IO-ENTE67] Add new io-fn-services-cache

- prod/westeurope/common/notification_hub_partition_1/terragrunt.hcl
- prod/westeurope/common/notification_hub_partition_2/terragrunt.hcl
- prod/westeurope/common/notification_hub_partition_3/terragrunt.hcl
- prod/westeurope/common/notification_hub_partition_4/terragrunt.hcl
Added four new Notification Hubs to enable partitioning.
In order to handle more than 10ml of users, we need to create four Notification Hub partitions
---
> [IP-146] Create new Notification Hubs for partitioning

- prod/westeurope/internal/api/functions_servicescache_r3/web_test/terragrunt.hcl
fix web test url for fn-services-cache
bad url
---
> Fix fn-services-cache webtest

- prod/westeurope/common/cdn/cdn_endpoint_iopay_web_test/terragrunt.hcl
- prod/westeurope/common/cdn/cdn_endpoint_iopayportal_web_test/terragrunt.hcl
- prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_iopayportal/web_test/terragrunt.hcl
- availability test for `io pay`;
- availability test for `pay portal`;
The goal of these _availability test_ is to check the availability of the frontend applications invoking every 300 seconds:
- `iopay-custom-domain/index.html`
- `iopayportal-custom-domain/index.html`
and checking the status code 200.
---
> [IOPAY-109] Availability test for io-pay and io-pay-portal

- prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/storage/table_faileduserdataprocessing/terragrunt.hcl
Added env vars for failed user data processing table
Needed for:
https://github.com/pagopa/io-functions-admin/pull/138
---
> [#ip-145] env vars for failed user data processing table

- prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl
- prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
Enable FF "all" (already applied)
Final step of NH migration
---
> [#IP-115] Enable FF all for fn-pushnotif (already applied)

- prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
- prod/westeurope/common/cdn/cdn_endpoint_iopayportal/terragrunt.hcl
- Updated _Content Security Policy_ for _io-pay_ and _io-pay-portal_;
The goal of this PR is to update the _Content Security Policy_ for _io-pay_ and _io-pay-portal_  in order to divide the _Content Security Policy_  header into several blocks, each with at most 128 characters.
---
> [IOPAY-220] Refactoring csp io-pay

- prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
- Updated _Content Security Policy_ for _io-pay_ ;
The goal of this PR is to update the _Content Security Policy_ for _io-pay_ to allow:
- iframe (to support 3ds2 flow);
- image from Payment Manager;
---
> [IOPAY-220] update csp io-pay

- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
- Added apim subnet to function app eucovidcert
Bootstrap of new _Green pass_ project
---
> [#IP-197] Add apim subnet to eucovidcert function app

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/web_test/terragrunt.hcl
Add web test to fn-services
Improve observability
---
> [#IOINFRA-109] Add web test to fn-services

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/testusersvars.hcl
* Store test users' fiscal code in common variables for all `appbackend` instances
* Split different sets by their scopes
We will need to add several more fiscal codes, this refactor aims to better organize them.
---
> [#IPV-13] Refactor to allow more test users

- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
Add SLOT_TASK_HUBNAME variable to fn-eucovidcert (prod and staging)
---
> Add SLOT_TASK_HUBNAME variable

- prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
- prod/westeurope/common/cdn/cdn_endpoint_iopayportal/terragrunt.hcl
- changed _CSP header_ to enable _Content Security Policy_ (previously in _Report-Only_ mode);
---
> [IOPAY-220] Enable CSP

- prod/westeurope/internal/api/apim/api_management_api_services/api/swagger.json.tmpl
* Update OpenAPI spec to include `eu_covid_cert` payload in message content
---
> [#IP-214] Update API Specification for services APIM

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
Added new env variables and URLs for fn-eucovidcert in io-backend
Please try 
---
> Add new env variables for eucovidcert

- prod/westeurope/internal/api/cosmosdb/account/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/services/functions_services01_r3/function_app/terragrunt.hcl
- prod/westeurope/services/functions_services01_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/services/functions_services01_r3/subnet/terragrunt.hcl
- prod/westeurope/services/functions_services01_r3/web_test/terragrunt.hcl
- prod/westeurope/services/resource_group/terragrunt.hcl
1. Add new fn-services01
From performance test we need to scale out fn-services with more function app to avoid delay in send messaged flow.
Load balancer configuration in next pull request
---
> Add new fnservices01

- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
* add env variables from vault containing CA certificates for connecting to DGC service
---
> Add CA to eucovidcert function app

- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
We need code changes before apply this pr
---
> Add url routing for fneucovidcert

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl
- prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/services/functions_services01_r3/function_app/terragrunt.hcl
- prod/westeurope/services/functions_services01_r3/function_app_slot_staging/terragrunt.hcl
> Scale out durable functions

- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
> Align fn async config for eucovidcert

- prod/westeurope/internal/api/cosmosdb/container_message-status/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_messages/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_notification-status/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_notifications/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_profiles/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_services/terragrunt.hcl
> Scaleout cosmosdb

- prod/westeurope/common/nat_gateway/terraform.tf
- prod/westeurope/common/nat_gateway/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/eucovidcert/storage_eucovidcert/queue_notify-new-profile-poison/terragrunt.hcl
- prod/westeurope/eucovidcert/storage_eucovidcert/queue_notify-new-profile/terragrunt.hcl
- prod/westeurope/eucovidcert/storage_eucovidcert/table-trace-notify-new-profile/terragrunt.hcl
> Nat gateway function covidcert integration

- prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
set IS_CASHBACK_ENABLED = "false" on fn3apps
Cashback suspended
---
> Disable cashback welcome message

- prod/westeurope/internal/api/cosmosdb/container_service-preferences/terragrunt.hcl
* Add `service-preferences` Cosmos container definition
We need this to store User's preferences on Service subscriptions
---
> [#IP-264] Add service-preferences container

- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
deactivate fn-services01 from fn-covidcert
---
> [#IOINFRA-118] remove fn-services01 from fn-covidcert

- prod/testusersvars.hcl
* Add some more fake fiscal codes to be used as fake users in app
Have some internal user to be used in e2e testing
---
> Add fake users for internal testing

- .gitignore
- prod/westeurope/internal/api/apim/api_management_api_io_payportal/api/policy.xml
- prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
For a brand new newsletter on present pagopa.gov.it website and the new pagopa.it we need to add new groups param and website urls.
- policy.xml : added the urls of the new corporate website (prod and stage)
- terragrount.hcl : updated groups param and allowed lists
This PR is needed to connect website to recaptcha check function
---
> Recaptcha update data to serve diff. newsletters

- prod/westeurope/operations/vm_instabug/subnet/terragrunt.hcl
- prod/westeurope/operations/vm_instabug/vm/backend.tf
- prod/westeurope/operations/vm_instabug/vm/terragrunt.hcl
> Add instabug vm

- prod/westeurope/internal/developerportalbackend/app_service/terragrunt.hcl
ENTE-40 dev an approval workflow for in app service 
Dev portal environment variables for JIRA integration
increases speed of service integration in IO App
> [#ENTE-40] Dev Portal - add env variables for workflow by jira

- prod/westeurope/internal/api/cosmosdb/container_message-status/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_messages/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_notification-status/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_notifications/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_profiles/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/container_services/terragrunt.hcl
scale down cosmos ru collection
cost saving
---
> [#IOINFRA-112] Scale down cosmosdb-api

- prod/westeurope/common/public_dns_zones/io_pagopa_it/dns_caa_record/terragrunt.hcl
- prod/westeurope/common/public_dns_zones/io_pagopa_it/terragrunt.hcl
- prod/westeurope/common/public_dns_zones/io_pagopa_it/zone/terragrunt.hcl
add new public dns zone `.io.pagopa.it`
switch to a dns zone owned by PagoPA
---
> Add new public dns zones .io.pagopa.it

- prod/westeurope/operations/functions_slackbot/subnet/terragrunt.hcl
add slackbot subnet
set manual vnet integration for fn-slackbot due to close public access cosmosdb
---
> [#IOINFRA-175] Add slackbot subnet

- prod/westeurope/operations/logic-apps/logic-app-privacy-get-profiles/terragrunt.hcl
- prod/westeurope/operations/logic-apps/logic-app-privacy-upsert-user-data-processing/terragrunt.hcl
upgrade logic app to terraform 0.14
logic app outbound ip changed. We need updated outbound ip to whitelist it into cosmosdb-api
---
> [#IOINFRA-174] Upgrade logic app terraform

- prod/westeurope/common/dns_forwarder/server/terragrunt.hcl
- prod/westeurope/common/dns_forwarder/subnet/terragrunt.hcl
add dns forwarder
no more need to set file host to resolve private DNS
---
> [#IOINFRA-179] Add DNS forwarder

- prod/westeurope/common/subnet_pendpoints/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/account/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/private_dns_a_record/terragrunt.hcl
- use subnet instead slackbot ips
- align terraform code with azure configuration (`enforce_private_link_endpoint_network_policies = true`, `dependency.private_dns_zone.outputs.name`)
---
> Align network configs

- prod/westeurope/common/private_dns_zones/privatelink-blob-core-windows-net/virtual_network_link_vnet-common/terragrunt.hcl
- prod/westeurope/common/private_dns_zones/privatelink-blob-core-windows-net/zone/terragrunt.hcl
- prod/westeurope/common/private_dns_zones/privatelink-file-core-windows-net/virtual_network_link_vnet-common/terragrunt.hcl
- prod/westeurope/common/private_dns_zones/privatelink-file-core-windows-net/zone/terragrunt.hcl
- prod/westeurope/common/private_dns_zones/privatelink-queue-core-windows-net/virtual_network_link_vnet-common/terragrunt.hcl
- prod/westeurope/common/private_dns_zones/privatelink-queue-core-windows-net/zone/terragrunt.hcl
- prod/westeurope/common/private_dns_zones/privatelink-table-core-windows-net/virtual_network_link_vnet-common/terragrunt.hcl
- prod/westeurope/common/private_dns_zones/privatelink-table-core-windows-net/zone/terragrunt.hcl
add private DNS zones for storage accounts
---
> [#IOINFRA-182] Add private DNS zone for storage account

- prod/westeurope/internal/api/storage/private_endpoint_blob/terragrunt.hcl
- prod/westeurope/internal/api/storage/private_endpoint_file/terragrunt.hcl
- prod/westeurope/internal/api/storage/private_endpoint_queue/terragrunt.hcl
- prod/westeurope/internal/api/storage/private_endpoint_table/terragrunt.hcl
add private endpoint to iopstapi
add private endpoint private dns record
limits comosapi network access
---
> [#IOINFRA-185] Add private endpoint iopstapi

- prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
* update Node runtime to 14.16.0
* configure healthcheck endpoint
Update to latest available Node version
---
> [#IP-344] update node version to `fn3-admin`

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
remove scale setting
cost saving
---
> Scale down fn-services

- prod/westeurope/internal/api/functions_public_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_public_r3/function_app_slot_staging/terragrunt.hcl
* update Node runtime to 14.16.0
* configure healthcheck endpoint
Update to latest available Node version
---
> [IP-351] Update Node version to `fns-public`

- prod/westeurope/internal/api/functions_assets_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_assets_r3/function_app_slot_staging/terragrunt.hcl
* update Node runtime to 14.16.0
* configure healthcheck endpoint
Update to latest available Node version
---
> [IP-347] Update Node version to `fns-assets`

- prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl
- prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
> Scale down push notif

- prod/westeurope/internal/developerportalbackend/app_service/terragrunt.hcl
ENTE-124 add more metadata to Jira Card
Dev portal environment variables for JIRA integration
with this PR Jira Card has information about Delegate, Delegate Email and Organization Name
> [ENTE-124] Custom field variable name added

- prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
* update Node runtime to 14.16.0
* configure healthcheck endpoint
Update to latest available Node version
---
> [IP-345] Update Node version on `fn3-app`

- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
add healthcheck
resiliency
---
> Add health check fn-eucovidcert

- prod/westeurope/notifications/functions_pushnotif/function_app/terragrunt.hcl
- prod/westeurope/notifications/functions_pushnotif/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/notifications/functions_pushnotif/subnet/terragrunt.hcl
> Private storage for fn-pushnotif durable function

- prod/westeurope/internal/api/functions_servicescache_r3/function_app/terragrunt.hcl
use new function app module to close internet access for durable function
---
> Private storage for fn-servicescache durable function

- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
> Func appasync private storage

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/subnet/terragrunt.hcl
- prod/westeurope/cgn/storage_cgn/queue_eycaactivations/terragrunt.hcl
> Func cgn private storage

- prod/westeurope/cgn/cosmosdb/account/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb/account/terragrunt.hcl
- prod/westeurope/internal/api/cosmosdb_bonus/account/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_assets_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_assets_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonusapi_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonusapi_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_public_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_public_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_servicescache_r3/function_app/terragrunt.hcl
> Rotate cosmosdb keys

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_admin_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_assets_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_assets_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonusapi_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonusapi_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_public_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_public_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_servicescache_r3/function_app/terragrunt.hcl
> Function app switch to primary master key

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
Upgrade default node version according to https://github.com/pagopa/io-functions-cgn/pull/51
Required in order to upgrade all functions to the same node version
---
> [#IP-381] Upgrade default node version to 14.16.0 for IO Functions CGN

- prod/westeurope/cgn/functions_cgn_merchant/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_assets_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_bonus/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_public_r3/function_app/terragrunt.hcl
> Disable threat protection storage accounts

- prod/westeurope/cgn/functions_cgn_merchant/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn_merchant/function_app_slot_staging/terragrunt.hcl
Upgrade default node version related to https://github.com/pagopa/io-functions-cgn-merchant/pull/6
Required to upgrade to the last supported node version by Functions runtime
---
> [#IP-382] Upgrade default node version to 14.16.0 on IO Functions CGN Merchant

- prod/westeurope/support/functions_backoffice/function_app/terragrunt.hcl
- prod/westeurope/support/private_dns_zone/zone/terragrunt.hcl
- prod/westeurope/support/private_dns_zone_cstar_pagopa/zone/terragrunt.hcl
- add new internal dns (postgres and apim)
- change secrets configs
- change CSTAR_API_URL
cstar migration
---
apply fn-backoffice only after cstar db migration
> Add new cstar configs

- prod/westeurope/support/private_dns_zone/zone/terragrunt.hcl
update postrgres replica ip
---
> Update postgres replica ip for support dashboard

- prod/westeurope/internal/api/apim/api_management_groups/terragrunt.hcl
Added `ApiMessageWriteWithPayee` group. This is related to [this](https://github.com/pagopa/io-functions-commons/pull/216)
- `api_management_groups`
Added new group to manage payment messages with explicit payee
---
> [#IP-189] - Add ApiMessageWriteWithPayee group

- prod/westeurope/common/cdn/cdn_endpoint_iopay/terragrunt.hcl
- add UAT _Payment Manager_ host in io-pay _Content Security Policy_
The goal of this PR is to add the Payment Manager host into the Content Secury Policy of io-pay cdn, for testing purposes.
---
> [IOPAY] Add PM uat env in iopay csp

- prod/external_resources.tf
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/developerportalbackend/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
add externals allowed_subnets
---
> add externals allowed_subnets

- prod/westeurope/external/pagopaproxyprod/app_service/terragrunt.hcl
- prod/westeurope/external/pagopaproxytest/app_service/terragrunt.hcl
- add new env for:
- pagopaproxytest
- pagopaproxyprod
The goal of this PR is to add a new feature flag in order to disable payments NM3 according to [this solution.](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/389288324/Classificazione+FaultCode+per+IO#Workaround-temporaneo)
---
> [PPR-162] add feature flag for pagopaproxy test/prod

- prod/westeurope/internal/api/functions_iopayportal/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_iopayportal/function_app_slot_staging/terragrunt.hcl
> Fix missed dependency storage io pay

- prod/westeurope/external/pagopaproxytest/autoscaling/terragrunt.hcl
> add autoscale pagopaproxytest

- prod/westeurope/external/pagopaproxytest/app_service/terragrunt.hcl
- enable NM3 for test environment
---
> [PPR-162] enable nm3 payments for test environment

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app/terragrunt.hcl
- prod/westeurope/eucovidcert/functions_eucovidcert/function_app_slot_staging/terragrunt.hcl
> add allow from apim subnets

- prod/westeurope/external/apigad/app_service/terragrunt.hcl
- prod/westeurope/external/pagopaproxyprod/autoscaling/terragrunt.hcl
- prod/westeurope/external/pagopaproxytest/autoscaling/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/autoscaling/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/autoscaling/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/autoscaling/terragrunt.hcl
add autoscaling for appbackendli
add autoscaling for pagopaproxyprod
scale in apigad to plan p2v1
change plan for appbackendl* to p1v3
---
> App service improvements

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_servicescache_r3/function_app/terragrunt.hcl
add queues for internal usage
---
> [IC-88] create service queue

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
add internal container for fn-services and policy to delete blobs older then 1 day
---
> Add internal container fn services

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
> add poison queue

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
refactor connection strings
https://github.com/pagopa/io-functions-services/pull/170
---
> refactor connection strings

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
disable queue triggered function on slot
- ProcessMessage
- CreateNotification
- EmailNotification
- WebhookNotification
- OnFailedProcessMessage
---
> disable queue trigger on slot

- prod/westeurope/external/pagopaproxyprod/app_service/terragrunt.hcl
- Enable feature flag NM3_ENABLED
The goal of this PR is to enable NM3 payments for pagopa-proxy.
---
> Enable NM3 payments for pagopa-proxy

- prod/westeurope/external/pagopaproxyprod/app_service/terragrunt.hcl
> Disable nm3 for pagopa-proxy

- prod/westeurope/external/pagopaproxyprod/app_service/terragrunt.hcl
> enable nm3

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
> lowered eyca upper age bound to allow testing on cgn only

- prod/westeurope/external/pagopaproxyprod/app_service/terragrunt.hcl
> Enable nm3 pagopa-proxy

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
removed old app gateway subnet
fix
---
> remove old app gateway subnet

- prod/westeurope/internal/api/apim/api_management_api_admin/swagger.json.tmpl
- prod/westeurope/internal/api/apim/api_management_api_services/api/swagger.json.tmpl
- prod/westeurope/internal/api/apim/api_management_groups/terragrunt.hcl
- Add MVL UserGroups
- Align fn-services-spec
- Align fn-admin
Changes needed by MVL management
---
> [#IC-67] add mvl management

- prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl
- prod/westeurope/functions_app1/functions_app1_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app_slot_staging/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app_slot_staging/terragrunt.hcl
- add VISIBLE_SERVICE_BLOB_ID
performance issue
---
> Add VISIBLE_SERVICE_BLOB_ID to fn3apps

- prod/westeurope/functions_app1/functions_app1_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app2_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_app_async/function_app/terragrunt.hcl
> fix fn3apps conf

- prod/westeurope/internal/api/apim/api_management_api_services/api/swagger.json.tmpl
Added to the APIM openapi template the new APIs for services Activation (special services).
The new APIs to get and upsert `Activation` exposed by `io-functions-services` must be binded in APIM.
---
> [#IC-161] Update APIM fn-services api specs for Activation endpoints

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
> Pec server token issuer app settings in all app backends

- prod/westeurope/internal/developerportalbackend/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
> New env vars for cgn

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
> env fixes for cgn

- prod/westeurope/internal/developerportalbackend/app_service/terragrunt.hcl
* update node version to 14.x
New library added aren't compatible with node 6.x anymore
---
> [#IC-160] Update Developer Portal node version

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
> [#IC-180] Fixed CGN paths

- prod/westeurope/cgn/functions_cgn/function_app/terragrunt.hcl
- prod/westeurope/cgn/functions_cgn/function_app_slot_staging/terragrunt.hcl
This PR adds a new env variable on io-functions-cgn.
- add CGN_SERVICE_ID on secrets for func-cgn-staging slot
- add CGN_SERVICE_ID on secrets for func-cgn-production slot
This  is needed to enable CGN to be recognized as special service.
---
> add CGN_SERVICE_ID env variable

- prod/westeurope/linux/appbackendl1/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/autoscaling/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/subnet/terragrunt.hcl
- prod/westeurope/linux/appbackendl1/web_test/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/autoscaling/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/subnet/terragrunt.hcl
- prod/westeurope/linux/appbackendl2/web_test/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service/terragrunt.hcl
- prod/westeurope/linux/appbackendli/app_service_slot_staging/terragrunt.hcl
- prod/westeurope/linux/appbackendli/autoscaling/terragrunt.hcl
- prod/westeurope/linux/appbackendli/subnet/terragrunt.hcl
- prod/westeurope/linux/appbackendli/web_test/terragrunt.hcl
- prod/westeurope/linux/resource_group/terragrunt.hcl
Deprecated resources moved in io-infra
---
> Deprecate app backend

- prod/westeurope/external/firewall_custom_rules/terragrunt.hcl
Please see internal report for FP details.
> Disable some Java rules that may trigger FP in some unlikely cases

- prod/westeurope/common/cdn/cdn_endpoint_fnassets/terragrunt.hcl
> Add TTL cache for zendesk

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
Add variable configuration for APIM to connect to payment-update: it will allow to retrieve payment status in the GetMessage.
add apim url variable
add apim subscription for io-fn-service variable
Premium Service have to retrtieve also the payment status when retrieving a payment message
---
> [#ICC-103] Add APIM endpoint to connect to payment-updater

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
* Add ttl value in `functions_services_r3`;
In order to set the ttl to the value of 3 years for message and message-status for those messages sent to users that are not found, we want to add this value in settings.
---
> Add ttl value in functions_services settings

- prod/westeurope/internal/api/functions_services_r3/function_app/terragrunt.hcl
- prod/westeurope/internal/api/functions_services_r3/function_app_slot_staging/terragrunt.hcl
* set FF_DISABLE_WEBHOOK_MESSAGE_CONTENT to false
In order to keep this repo aligned with the infrastructure
---
> set FF_DISABLE_WEBHOOK_MESSAGE_CONTENT to false
